---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Installing pre dependencies of xorg-server
  include: pre_install.yaml

- name: Merge pre defined xorg packages and packages defined by user
  set_fact:
    xorg_packages: "{{ __xorg_packages|list }}"
  when: xorg_packages is not defined

- name: Set the default display manager xdm
  set_fact:
    xorg_display_manager_package: "{{ __xorg_display_manager_package }}"
  when: xorg_display_manager_package is not defined

- name: Set the default display manager service name
  set_fact:
    xorg_display_manager_service: "{{ __xorg_display_manager_service }}"
  when: xorg_display_manager_service is not defined

- name: Merge default fonts and user defined font
  set_fact:
    xorg_fonts: "{{ __xorg_fonts|list }}"
  when: xorg_fonts is not defined

- name: Installing xorg-server and sufficient packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ xorg_packages }}"

- name: Setting Start X service
  template:
    src: x11.service.j2
    dest: /etc/systemd/system/x11.service
    owner: root
    group: root
    mode: 0644

- name: Setting noblank
  template:
    src: noblank.service.j2
    dest: /etc/systemd/system/noblank.service
    owner: root
    group: root
    mode: 0644

- name: Setting noblank
  template:
    src: noblank.sh.j2
    dest: /usr/local/bin/noblank.sh
    owner: root
    group: root
    mode: 0755

- name: Setting firefox X service
  template:
    src: firefox.service.j2
    dest: /etc/systemd/system/firefox.service
    owner: root
    group: root
    mode: 0644

- name: Installing xorg-font and user chosen fonts
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ xorg_fonts }}"
  notify: Restart display manager

- name: Enable "X11"
  service:
    name: x11
    enabled: True
    state: started

- name: Enable "firefox"
  service:
    name: firefox
    enabled: True
    state: started

- name: Enable "noblank"
  service:
    name: noblank
    enabled: True
    state: started

- name: Enable "X11"
  service:
    name: x11
    enabled: True
    state: restarted
